apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-todo-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream flask_todo {
        server flask-todo-service:5000;
      }
      server {
        listen 80;
        server_name localhost;

        location / {
          proxy_pass http://flask_todo;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-todo-lb
  labels:
    app: nginx-todo-lb
spec:
  selector:
    matchLabels:
      app: nginx-todo-lb
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-todo-lb
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-master
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-todo-config