apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      upstream flask-todo {
        server flask-todo:5000;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://flask-todo;
        }
      }
    }