apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-todo
  labels:
    app: postgres-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-todo
  template:
    metadata:
      labels:
        app: postgres-todo
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-db
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "dbPassword"
        - name: POSTGRES_DB
          value: "todo"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-todo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres-todo
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-todo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-todo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi