apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: {{ .Release.Name }}-db
type: Opaque
data:
  PG_USER: {{ .Values.secrets.postgres.PG_USER | b64enc }}
  PG_PASSWORD: {{ .Values.secrets.postgres.PG_PASSWORD | b64enc }}
  PG_DB: {{ .Values.secrets.postgres.PG_DB | b64enc }}