apiVersion: v1
kind: Service
metadata:
  name: mybackend-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.backendPort }}
      nodePort: {{ .Values.service.backendNodePort }}
  selector:
    app: {{ .Release.Name }}-backend
