apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      nodeSelector:
        role: app
      containers:
      - name: flask-todo
        image: danielcristh0/flask-todo:1.1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://admin:dbPassword@db:5432/todo"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-todo
spec:
  selector:
    app: flask-todo
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP