apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream flask {
        server flask-todo:5000;
    }

    server {
        listen 8082;

        location / {
            proxy_pass http://flask;
        }
    }